# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-05 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20170205_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=14, verbose_name='Telefone'),
        ),
    ]
