# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-05 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20170205_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='reward',
            field=models.CharField(default='', max_length=200, verbose_name='Recompensa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardconfiguration',
            name='expire',
            field=models.IntegerField(verbose_name='Válidade do cartão em dias'),
        ),
        migrations.AlterField(
            model_name='cardconfiguration',
            name='limit',
            field=models.IntegerField(verbose_name='Limite de pontos para troca'),
        ),
    ]
