# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_card_expire_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Card')),
            ],
            options={
                'verbose_name_plural': 'Pontos',
                'verbose_name': 'Ponto',
            },
        ),
    ]
