# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20170207_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='expired',
            field=models.BooleanField(default=0, verbose_name='Expirado?'),
        ),
        migrations.AddField(
            model_name='card',
            name='reward',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Recompensa'),
        ),
    ]
