# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_auto_20170207_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Convertido em'),
        ),
    ]
