# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-11 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='/Applications/XAMPP/xamppfiles/htdocs/fideli.club/admin/admin/general/midia', verbose_name='Imagem'),
        ),
    ]
