# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-14 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_auto_20170211_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='', max_length=8, verbose_name=''),
            preserve_default=False,
        ),
    ]
