# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-14 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_client_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=8, verbose_name='Senha'),
        ),
    ]
