# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-18 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_auto_20170214_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('number', models.CharField(blank=True, max_length=5, verbose_name='Número')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('complement', models.CharField(blank=True, max_length=300, verbose_name='Complemento')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='Município')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name_plural': 'Endereços',
                'verbose_name': 'Endereço',
            },
        ),
    ]
